config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  get "/profile", to: 'pages#profile'
  
  root to: 'pages#home'
  resources :cards do
    resources :favorites, only: [:index, :create]
    resources :comments, only: [:create, :update]
    resources :votes, only: [:create, :destroy]
  end
  resources :comments, only: :destroy
  resources :favorites, only: :destroy
  resources :decks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="nav-bar">
  <div class="user-nav">
    <div class="home-btn">
      <%= link_to (image_tag "ghost_logo.png", class: "home-logo"), root_path %>
      <small>home</small>
    </div>
    <i class="fas fa-search filter-menu" data-toggle="modal" data-target="#exampleModal"></i>
    <% if current_user %>
        <div class="nav-item dropdown home-btn">
          <%= cl_image_tag current_user.photo.key, class: "user-avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <small>menu</small>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown" id="menu-profile">
            <%= link_to "Dashboard", profile_path, class: "dropdown-item" %>
            <%= link_to "Create a card", new_card_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </div>
    <% else %>
      <div class="home-btn">
        <div class="button-signin">
          <%= link_to "Sign\nIn", new_user_session_path, class: 'btn-signin' %>
        </div>
        <small>sign in</small>
      </div>
    <% end %>
  </div>
</div>


<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Select Cards Categories</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag cards_path, method: :get do %>
          <%= select_tag :category,
            options_for_select(['Tricks', 'Weapons']),
            class: "form-control",
            prompt: "Select a category:"
          %>
          <%= select_tag :level,
            options_for_select(['Beginner', 'Intermediate', 'Confirmed']),
            class: "form-control",
            prompt: "Select your trick level:"
          %>
          <%= submit_tag "Search", class: "btn btn-primary" %>
      <% end %>
      </div>
    </div>
  </div>
</div>