config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  get "/profile", to: 'pages#profile'
  
  root to: 'pages#home'
  resources :cards do
    resources :favorites, only: [:index, :create]
    resources :comments, only: [:create, :update]
    resources :votes, only: [:create, :destroy]
  end
  resources :comments, only: :destroy
  resources :favorites, only: :destroy
  resources :decks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :creator, class_name: "User", foreign_key: "user_id"

  has_rich_text :content

  has_one_attached :photo

  has_many :favorites, dependent: :destroy
  has_many :decks, through: :favorites
  has_many :votes, dependent: :destroy
  has_many :comments

  scope :category, ->(category) { Card.where(category: category) }
  scope :level, ->(level) { Card.where(level: level) }

  validates :title, presence: true
  validates :category, presence: true
  validates :content, presence: true
  validate :level_if_tricks
  validate :text_content

  include PgSearch::Model
  pg_search_scope :search_by_word, against: %i[title content category level], using:
      { tsearch:
        { prefix:
          true } }

  def level_if_tricks
    errors.add(:level, "Should not be empty") if category == "Tricks" && level.blank?
  end

  def text_content
    errors.add(:content, "Should be longer!") if content.body.to_plain_text.length < 42
  end

  def upvotes
    votes.where(status: 'upvote').size
  end

  def downvotes
    votes.where(status: 'downvote').size
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[home index show]
  def index
    @cards = Card.all.order("id DESC")

    @cards = @cards.category(params[:category]) if params[:category].present?
    @cards = @cards.level(params[:level]) if params[:level].present?
  end

  def new
    @card = Card.new
  end

  def create
    @card = Card.new(card_params)
    @card.creator = current_user

    @card.save ? (redirect_to @card) : (render "new")
  end

  def destroy
    @card = Card.find(params[:id])
    @card.destroy ? (flash[:alert] = "card deleted.") : (flash[:error] = "Something went wrong.")
    redirect_to profile_path
  end

  def show
    @card = Card.find(params[:id])
    @comment = Comment.new
    @comments = @card.comments
  end

  private

  def card_params
    params.require(:card).permit(:title, :content, :category, :level, :photo)
  end
end

app/views/cards/index.html.erb
<div>
  <h1>All tips</h1>
</div>
<div class="cards">
  <div class="card">
    <% @cards.each do |card| %>
      <div class="card-selector">
        <div class="card-title">
          <div class="toggle-info details">
            <span class="left"></span>
            <span class="right"></span>
          </div>
        <h2><%= card.title %></h2>
        </div>
        <div class="hid-content hidden">
          <div class="card_image-holder">
            <%= cl_image_tag card.photo.key, max_width: 250, crop: :fill %>
          </div>
          <div class="card-description target">
            <%= card.content %>
          </div>
          <div class="card-actions">
            <%= link_to "View More", card_path(card.id), class: "details" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="button-index" id="rounded-btn">
  <%= link_to "Create Card", new_card_path, class: 'btn-index' %>
</div>

<% content_for :meta_title, "#{@cards.last.title} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @cards.last.content %>
<% content_for :meta_image, cl_image_path(@cards.last.photo.key) %>

app/views/cards/new.html.erb
<div class="create-card-container">
  <div class="form-border">
    <%= simple_form_for @card do |f| %>
      <%= f.input :title, maxlength: 20 %>
      <%= f.input :category, collection: ["Tricks", "Weapons"], input_html: { id: "category" } %>   
      <%= f.input :level, collection: ["Beginner", "Intermediate", "Confirmed"], wrapper_html: { class: 'hidden', id: "level" } %>
      <%= f.input :photo, as: :file %>
      <%= f.input :content, as: :rich_text_area, class: "form-control" %>
        <div class="button-index">
          <%= f.submit "Submit", class: "btn-index" %>
        </div>
    <% end %>
  </div>
</div>

app/views/cards/show.html.erb
<div class="show-card">
  <div class="cards">
    <div class="card">
      <div class="card-title">
        <h2><%= @card.title %></h2>
      </div>
      <div class="hidden-content">
        <div class="level-category">
          <% if @card.category == "Weapons" %>
            <img id="ak-icon" src="https://img.icons8.com/ios-filled/50/000000/assault-rifle.png"/>
          <% else %>
            <i class="fas fa-book"></i>
          <% end %>
          <% if @card.level == "Beginner" %>
            <div class="d-flex">
              <h4>Level : </h4>
              <img id="stars" src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/US-O7_insignia.svg/200px-US-O7_insignia.svg.png" alt="stars">
            </div>
          <% elsif @card.level == "Intermediate" %>
            <div class="d-flex">
              <h4>Level : </h4>
              <% 2.times do %>
                <img id="stars" src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/US-O7_insignia.svg/200px-US-O7_insignia.svg.png" alt="stars">
              <% end %>
            </div>
          <% elsif @card.level == "Confirmed" %>
            <div class="d-flex">
              <h4>Level : </h4>
              <% 3.times do %>
                <img id="stars" src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/US-O7_insignia.svg/200px-US-O7_insignia.svg.png" alt="stars">
              <% end %>
            </div>
          <% end %>
        </div>

        <div class="card_image-holder">
          <%= cl_image_tag @card.photo.key, max_width: 250, crop: :fill %>
        </div>
        <div class="card-description">
          <%= @card.content %>
        </div>
        <hr>
        <div class="bottom-card">
          <div class="votes" data-controller="votes" data-votes-card-id-value="<%= @card.id %>">
            <i class="fas fa-angle-double-up <%= current_user.upvoted?(@card) ? 'upvoted' : '' %> " data-action="click->votes#upvote"></i>
            <div class="upvotes-counter" data-votes-target="upcounter">
              <%= @card.votes.where(status: 'upvote').count %>
            </div>
            <p class="mx-1 mb-0">|</p>
            <div class="downvotes-counter" data-votes-target="downcounter">
              <%= @card.votes.where(status: 'downvote').count %>
            </div>        
            <i class="fas fa-angle-double-down <%= current_user.downvoted?(@card) ? 'downvoted' : '' %> " data-action="click->votes#downvote"></i>
          </div>
          <div class="button-deck">
            <button type="button" class="btn-deck" data-toggle="modal" data-target="#deckModal">
              Add to deck
            </button>
          </div>
          <div class="creator">
            <p><small>Creator: </small><br><%= @card.creator.username %> </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<h2>Comments : (<%= @card.comments.count %>)</h2>

  <div class="display-comments">
      <% @card.comments.each do |comment| %>
        <div class="display-comment">
          <div class="user-title">
            <div class="user-img">
              <%= cl_image_tag comment.creator.photo.key, id: "user-avatar" %>
            </div>
            <h2><%= comment.creator.username %> : </h2>
          </div>
          <hr>
          <p><%= comment.content %></p>
        </div>
      <% end %>
  </div>

<h2>Add a comment :</h2>

<div class="create-comment-container">
  <div class="form-border">
    <%= simple_form_for([@card, @comment], method: :post) do |f| %>
      <%= f.input :content, as: :rich_text_area, label: false %>
      <%= f.submit class: "btn-index" %>
    <% end %>
  </div>
</div>

<div class="modal fade" id="deckModal" tabindex="-1" role="dialog" aria-labelledby="deckModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deckModalLabel">Add this card to your deck</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag card_favorites_path(@card), method: :post do %>
          <div>
            <%= select_tag :name,
              options_for_select(Deck.where(user: current_user).pluck(:name)),
              class: "form-control",
              prompt: "Select a deck to put this card in:"
            %>
          </div>
          <div class="">
            <%= submit_tag "Add", class: "btn btn-index" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>