config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  get "/profile", to: 'pages#profile'
  
  root to: 'pages#home'
  resources :cards do
    resources :favorites, only: [:index, :create]
    resources :comments, only: [:create, :update]
    resources :votes, only: [:create, :destroy]
  end
  resources :comments, only: :destroy
  resources :favorites, only: :destroy
  resources :decks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/deck.rb
class Deck < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :cards, through: :favorites
  validates :name, presence: true, uniqueness: true
end

# has_many :cards, through: :favorites
# SELECT * FROM cards
# INNER JOIN favorites ON cards.id = favorites.card_id
# WHERE favorites.deck_id = id

# Card.joins(:favorites).where(favorites: {deck_id: id})

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  def index
    @decks = Deck.all
  end

  def new
    @deck = Deck.new
  end

  def create
    @deck = Deck.new(deck_params)
    @deck.user = current_user

    @deck.save ? "Successfully added!" : "Something went wrong"
    redirect_to profile_path
  end

  def destroy
    @deck = Deck.find(params[:id])
    @deck.destroy ? "Deck deleted." : "Something went wrong."
    redirect_to profile_path
  end

  def show
    @deck = Deck.find(params[:id])
    @cards = @deck.cards
  end

  private

  def deck_params
    params.require(:deck).permit(:name)
  end
end

app/views/decks/_list.html.erb
<div>
  <h1>My decks</h1>
</div>
<div class="cards">
  <div class="card">
    <% @decks.each do |deck| %>
      <div class="card-selector" id="<%= dom_id(deck) %>">
        <div class="card-title">
          <div class="toggle-info details">
            <span class="left"></span>
            <span class="right"></span>
          </div>
          <%= link_to deck_path(deck), method: :delete, remote: true, data: { confirm: "Are you sure ?"} do %>
            <div class="delete-btn details" id="<%= deck.id %>">
              <span class="left"></span>
              <span class="right"></span>
            </div>
          <% end %>
        <h2><%= deck.name %> (<%= deck.cards.count %> cards)</h2>
        </div>
        <div class="hid-content hidden">
          <div class="card-description">
            <% deck.cards %>
          </div>
          <div class="card-actions">
            <%= link_to "Open Deck", deck_path(deck.id), class: "details" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/decks/show.html.erb
<div>
<h1>Your selection</h1>
</div>
<div class="cards">
  <div class="card">
    <% @cards.each do |card| %>
      <div class="card-selector">
        <div class="card-title">
          <div class="toggle-info details">
            <span class="left"></span>
            <span class="right"></span>
          </div>
          <% favorite = Favorite.find_by(deck: @deck, card: card) %>
          <%= link_to favorite_path(favorite), method: :delete, remote: true, data: { confirm: "Are you sure ?"} do %>
            <div class="delete-btn details" id="<%= card.favorites %>">
              <span class="left"></span>
              <span class="right"></span>
            </div>
          <% end %>
        <h2><%= card.title %></h2>
        </div>
        <div class="hid-content hidden">
          <div class="card_image-holder">
            <%= cl_image_tag card.photo.key, max_width: 250, crop: :fill %>
          </div>
          <div class="card-description target">
            <%= card.content %>
          </div>
          <div class="card-actions">
            <%= link_to "View More", card_path(card.id), class: "details" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>